FROM node:14.17.0

RUN yarn global add prisma

EXPOSE $PORT

WORKDIR /app
ADD reporter/package.json .
RUN yarn install

ADD reporter .
ADD prisma prisma

RUN prisma generate; yarn build

CMD yarn start