FROM node:14.17.0

RUN yarn global add prisma

EXPOSE $PORT

WORKDIR /app
ADD reporter/package.json .
RUN yarn install

ADD prisma prisma
ADD reporter .

RUN prisma generate; yarn build

CMD yarn start