FROM node:14.17.4

RUN yarn global add prisma

EXPOSE $PORT

WORKDIR /app
ADD reporter/package.json .
ADD reporter/yarn.lock .
RUN yarn install

COPY reporter .
COPY prisma prisma
RUN prisma generate; yarn build

CMD yarn start