import type { NextPage } from "next";
import { useRouter } from "next/router";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { gql } from "@apollo/client";
import client from "../apollo-client";

const Home: NextPage<{ a: string }> = ({ id }) => {
  const router = useRouter();

  const refreshData = () => {
    router.replace(router.asPath);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={refreshData}>Refresh</button>
        <div className={styles.grid}>{id}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query {
        getUser {
          id
        }
      }
    `,
  });
  return {
    props: {
      ...data.getUser
    },
  };
}

export default Home;
